### ISSUE TITLE
Snake Game is not woking fine

### ISSUE THREAD

**Issue by CodingSamm** [Sudhaanshuu/Sudhaanshuu#1]
It's not visible.

**Comment by Sudhaanshuu** [comment]
### Resolution Details:

Hi Team,

I have addressed the reported issue regarding the Snake Game not working as expected. After thorough debugging and testing, I identified the root cause of the problem and implemented the necessary fixes. The issue has been resolved, and the game is now functioning correctly.
### Actions Taken:

    Identified and fixed the bug: The issue was traced back to a specific section of the code that was not handling game logic properly. This has been corrected.
    Thorough testing: Post-fix, I performed extensive testing to ensure all functionalities are working as intended.
    Updated the repository: The latest changes have been pushed to the repository.
